version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    command: --skip-networking
    environment:
      MYSQL_ROOT_PASSWORD: RahulAbhi@1234
      MYSQL_DATABASE: updated_gold_price_prediction  # Optional: Create a specific database on startup
    networks:
      - my_network
    ports:
      - "3307:3306"  # Expose MySQL port for the app container
    volumes:
      - volume_database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

  app:
    build:
      context: .  # Build the app image from the current directory (Dockerfile present here)
    container_name: app-container
    depends_on:
      - mysql  # Ensures MySQL starts before the app
    networks:
      - my_network
    environment:
      DB_HOST: mysql  # Name of the MySQL service defined in docker-compose.yml
      DB_PORT: 3306  # Default MySQL port
      DB_USER: root  # User with access to your MySQL database
      DB_PASSWORD: RahulAbhi@1234  # Password for MySQL user
      DB_NAME: updated_gold_price_prediction  # The database you want to connect to

networks:
  my_network:
    driver: bridge

volumes:
  volume_database:
